// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1bgWXkgG_yzQcfy_L4Zd49K2ggSGtPwo',
    appId: '1:106373691759:web:bd79174258fc06b961509a',
    messagingSenderId: '106373691759',
    projectId: 'rent-a-car-73187',
    authDomain: 'rent-a-car-73187.firebaseapp.com',
    storageBucket: 'rent-a-car-73187.appspot.com',
    measurementId: 'G-P509JJLCY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTVeu3Eqyf_Hs7s2UaavIZwIFUOmpOHQs',
    appId: '1:106373691759:android:b512376e0d46ff2061509a',
    messagingSenderId: '106373691759',
    projectId: 'rent-a-car-73187',
    storageBucket: 'rent-a-car-73187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_EuKmWnoBRwa52xH4_N70joO5WVJRLc',
    appId: '1:106373691759:ios:84f0e71dda5f1c0b61509a',
    messagingSenderId: '106373691759',
    projectId: 'rent-a-car-73187',
    storageBucket: 'rent-a-car-73187.appspot.com',
    iosBundleId: 'com.example.rentACar',
  );
}
